; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
lib_deps = ESP32Servo

; To prevent IRAM & flash overflow?
; Reduce binary size, enable PSRAM fixes and strip unused functions
build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -Os
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -Wl,--relax
  -DCORE_DEBUG_LEVEL=0

; Use a larger partition layout to avoid flash/iram mapping issues
board_build.partitions = huge_app.csv